<?php

declare(strict_types=1);

namespace App\Http\Resources\Api\V1;

use App\Models\Author;
use App\Models\Category;
use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use JsonSerializable;

/**
 * Resource generated by alibori/laravel-api-resource-generator
 *
 * @property integer $id
 * @property integer $category_id
 * @property integer $author_id
 * @property string $title
 * @property string $description
 * @property Category $category
 * @property Author $author
 */
final class BookResource extends JsonResource
{
     /**
     * Transform the resource into an array.
     *
     * @param  Request  $request
     * @return array|Arrayable|JsonSerializable
     */
    public function toArray($request): array|JsonSerializable|Arrayable
    {
        return [
            'id' => $this->id,
			'category' => $this->whenLoaded('category', fn() => $this->category->name),
			'author' => $this->whenLoaded('author', fn() => $this->author->name),
			'title' => $this->title,
			'description' => $this->description,
        ];
    }
}
