<?php

declare(strict_types=1);

namespace App\Http\Resources\Api\V1;

use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use JsonSerializable;

/**
 * Resource generated by alibori/laravel-api-resource-generator
 *
 * @property integer $id
 * @property string $name
 * @property string $surname
 * @property string $email
 * @property string $phone
 * @property string $address
 * @property string $city
 * @property string $country
 * @property string $postal_code
 * @property string $avatar
 * @property integer $books_count
 * @property integer $loans_count
 * @property float $ratings_avg_rating
 * @property string $created_at
 */
final class UserResource extends JsonResource
{
     /**
     * Transform the resource into an array.
     *
     * @param  Request  $request
     * @return array|Arrayable|JsonSerializable
     */
    public function toArray($request): array|JsonSerializable|Arrayable
    {
        return [
            'id' => $this->id,
			'name' => $this->name,
			'surname' => $this->surname,
			'email' => $this->email,
			'phone' => $this->phone,
			'address' => $this->address,
			'city' => $this->city,
			'country' => $this->country,
			'postal_code' => $this->postal_code,
			'avatar' => $this->avatar,
            'total_books' => $this->whenCounted('books_count', $this->books_count),
            'total_loans' => $this->whenCounted('loans_count', $this->loans_count),
            'average_rating' => $this->whenAggregated('ratings', 'rating', 'avg'),
			'created_at' => $this->created_at
        ];
    }
}
